### ISSUE TITLE
Change background color for number card

### ISSUE THREAD

**Issue by joaopedros2** [piitaya/lovelace-mushroom-themes#52]
```type: custom:mushroom-number-card
card_mod:
  style: |-
    ha-card {
      --control-border-radius: 12px;
      --control-height: 36px;
      --control-button-ratio: 10;
      --control-icon-size: 0.5em;
      --bg-color: blue; #not work
    }
entity: input_number.shopping_item_number
name: none
layout: horizontal
fill_container: true
icon_type: none
display_mode: buttons
primary_info: none
secondary_info: none
tap_action:
  action: none
hold_action:
  action: none
double_tap_action:
  action: none

**Comment by piitaya** [comment]
Mushroom themes doesn't expose variable for that because the slider is using the color of the icon. You can set `icon_color: blue`. It will color the icon and the slider to blue. 

You should be able to add separate colors it using [DOM navigation](https://github.com/thomasloven/lovelace-card-mod#dom-navigation) from card mod. I'm not a card mod user so I can not help on that point.
